### PR TITLE
feat: codecov support

### PR DESCRIPTION
**Pull request by bilalcaliskan**
**What this PR does / why we need it:**
This PR adds codecov integration on unit testing

**Which issue(s) this PR related:**
Implements second task on #7 

**Special notes for your reviewer:**
This is my first PR to Trendyol open source, so i am very open to any kind of feedbacks!

### CODE REVIEW

**Comment by erkanzileli** [comment]
Thanks for the PR!

I triggered this workflow but I guess the report has some [issues](https://github.com/Trendyol/kink/pull/26/checks?check_run_id=3644457098#step:7:59).

Do you know why we are seeing this?

**Comment by bilalcaliskan** [comment]
@erkanzileli Thanks for approval. I guess [Codecov Github App](https://github.com/apps/codecov) is missing, are you authorized to add that integration on Trendyol account?

**Comment by developer-guy** [comment]
@bilalcaliskan thanks for the PR, looks great 🤝👌 Maybe as you said, @erkanzileli has not enough permissions to do that, I'll check it out ASAP. 🙋🏻‍♂️

**Comment by erkanzileli** [comment]
The app is added and I re-triggered but I guess it's still the same. Maybe because there are no tests currently or this change is not on the main branch.

Maybe we can merge it and see what happens.
WDYT @developer-guy @Dentrax

**Comment by bilalcaliskan** [comment]
@erkanzileli I think it's working now, i guess coverage seems %0 on readme because of that there are no tests yet as you mentioned. 

Thanks for merging!

**Pull request merged**
